CREATE OR REPLACE PROCEDURE DB2_FUN.BINARY_FILE_CHECKSUM_READ (
    IN P_FILE_NAME VARCHAR(255),
    OUTPUT CHECKSUM_RESULT CHAR(32)
)
LANGUAGE SQL
BEGIN
    SELECT FILE_RECORD_CHECKSUM INTO CHECKSUM_RESULT FROM DB2_FUN.BINARY_FILE_WITH_CHECKSUM WHERE FILE_RECORD_NAME = P_FILE_NAME;
END@
