CREATE OR REPLACE PROCEDURE DB2_FUN.ITEMS_WITH_NUMBER_UPSERT (
    IN P_ITEM_NAME VARCHAR(255),
    IN P_NUM SMALLINT
)
LANGUAGE SQL;
MODIFIES SQL DATA;
BEGIN
    DECLARE V_COUNT INT;

    -- Check if the record exists
    SELECT COUNT(*) INTO V_COUNT FROM DB2_FUN.ITEMS_WITH_NUMBER WHERE ITEM_NAME = P_ITEM_NAME;

    IF V_COUNT > 0 THEN
        -- Update the existing record
        UPDATE DB2_FUN.ITEMS_WITH_NUMBER
        SET NUM = P_NUM,
        WHERE ITEM_NAME = P_ITEM_NAME;
    ELSE
        -- Insert a new record
        INSERT INTO DB2_FUN.ITEMS_WITH_NUMBER (ITEM_NAME, NUM)
        VALUES (P_ITEM_NAME, P_NUM);
    END IF;
END@
