
DROP TABLE IF EXISTS DB2_FUN.ITEMS;
DROP TABLE IF EXISTS DB2_FUN.ITEMS_WITH_NUMBER;
DROP TABLE IF EXISTS DB2_FUN.BINARY_FILE_WITH_CHECKSUM;
BEGIN
    IF EXISTS (SELECT SCHEMANAME FROM SYSCAT.SCHEMATA WHERE SCHEMANAME = 'DB2_FUN') THEN
        EXECUTE IMMEDIATE 'DROP SCHEMA DB2_FUN RESTRICT';
    END IF;
END;

CREATE SCHEMA DB2_FUN AUTHORIZATION DB2INST1;

CREATE TABLE DB2_FUN.ITEMS (
    ITEM_NAME   VARCHAR(255) NOT NULL
);

CREATE TABLE DB2_FUN.ITEMS_WITH_NUMBER (
    ITEM_NAME   VARCHAR(255) NOT NULL,
    NUM         SMALLINT
);

CREATE TABLE DB2_FUN.BINARY_FILE_WITH_CHECKSUM (
    FILE_RECORD_NAME   VARCHAR(255) NOT NULL,
    FILE_RECORD                     BLOB(16777216) NOT NULL,
    FILE_RECORD_CHECKSUM            VARCHAR(32) NOT NULL
);